# Generated by Django 4.1.5 on 2023-01-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефонный номер')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Ссылка на Whats App')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес школы')),
                ('address_url', models.URLField(verbose_name='Ссылка на школу google maps')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
