# Generated by Django 4.1.5 on 2023-03-27 08:33

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_class_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Название')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_files', verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Аккредитация',
                'verbose_name_plural': 'Аккредитации',
            },
        ),
        migrations.AddField(
            model_name='aboutschool',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='gallery_images/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='class',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='gallery_images/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='progress',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='gallery_images/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='schoolhistory',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='gallery_images/', verbose_name='Фотография'),
        ),
    ]
